---
# tasks file for nginx
- name: "instalador nginx"
  apt:
    name:
      - nginx
    state: latest

- name: "start service"
  service:
    name: nginx
    state: started

# - name: "copy the nginx config file"
#   copy:
#     src: /home/ansible/ansible-vm/configs/nginx.conf
#     dest: /etc/nginx/sites-available/nginx.conf
#   become: yes

# - name: "create symlink"
#   file:
#     src: /etc/nginx/sites-available/nginx.conf
#     dest: /etc/nginx/sites-enabled/nginx.conf
#     state: link
#   become: yes

- name: "restart nginx"
  service:
    name: nginx
    state: restarted
  become: yes